### PR TITLE
[makefile] Update Vult to v0.4.15

### PR DESCRIPTION
**Pull request by SteveRussell33**
Using the v2 branch as this is the current version of VCV Rack

### CODE REVIEW

**Comment by modlfo** [comment]
I'm not sure why, but the version 4.14 of the vult compiler does not run correctly under QuickJs. For now it would be better to stick to 4.12.

**Comment by modlfo** [comment]
The version 0.4.15 that I just released should work.

**Comment by SteveRussell33** [comment]
Confirmed, updated commit.

**Comment by mxa** [comment]
merging untested

**Pull request merged**
