### PR TITLE
Polish up supercollider engine

### PR DESCRIPTION
**Pull request by mossheim**
@AndrewBelt finally got around to fixing up the build system. i tried to follow your comment suggestions, let me know how it looks. sorry for the delay!

### CODE REVIEW

**Comment by mossheim** [comment]
@AndrewBelt would you prefer i commit this directly to the v1 branch instead as other contributors have done? i am a bit hesitant to do that but will if you say so. :)

**Comment by mossheim** [comment]
@AndrewBelt just pushed this to v1 because it seems to be [your intended workflow](https://github.com/VCVRack/VCV-Prototype/pull/44#issuecomment-763158448), so i'll close this now.

**Comment by AndrewBelt** [comment]
Sorry, I don't have time to review this. However, since this would be adding a new engine, can it stay disabled (`SUPERCOLLIDER ?= 0`) until I have time to review it?

**Comment by mossheim** [comment]
Do you have a clear timeline in mind? If not, I don't want to continue waiting. I have tested this myself on macOS and Arch Linux and encountered no issues. I am watching this repo and will happily respond to any issues related to the SC engine.

**Pull request closed without merging**
