### PR TITLE
Faust support

### PR DESCRIPTION
**Pull request by sletz**
Here is a first version of Faust language support in VCV prototype. To simplify compilation, we are using the Interpreter backend, which can execute bytecode, but is obviously much slower compared to the LLVM backend. It should still be usable to prototype DSP. 

Feel free to use "squash merge" to combine all intermediate commits.

### CODE REVIEW

**Comment by AndrewBelt** [comment]
Hmm, I moved the `master` branch to `v1` and it automatically closed this PR. No worries, it'll be merged against `v1`.

**Comment by sletz** [comment]
Thanks. Do I have to do something on my side?

**Comment by AndrewBelt** [comment]
Sorry about the delay. Thanks for the PR. I've lightly tested this and merged it into `v1`. You now have direct commit rights, so commit future updates directly to `v1`.

**Comment by sletz** [comment]
Thanks !

**Pull request closed without merging**
